# Important Notes:
# Every field you add must be added to buildSrc/src/main/kotlin/multiloader-common.gradle.kts expandProps map.

# Project
version=0.11.2+26.1.2
group=ru.pinkgoosik.winterly
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Winterly
common_mainclassname=Winterly
fabric_mainclassname=WinterlyFabric
neoforge_mainclassname=WinterlyNeoForge
mod_author=Flechazo, PinkGoosik, VioletSomik
mod_id=winterly
license=MIT
credits=
description=Winter expansion mod adding cold and sloppy stuff.
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.151.0+26.1.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.75
neoforge_loader_version_range=[4,)

# Release Publishing
release_type=release
# Valid values: client / server / both
release_dist=both
# Used by both Modrinth and CurseForge publishing tasks (supports multiline with \n)
release_changelog=No changelog was specified.
modrinth_project=
modrinth_project_fabric=
modrinth_project_neoforge=
curseforge_project=
curseforge_project_fabric=
curseforge_project_neoforge=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
